load("@rules_java//java:java_library.bzl", "java_library")
load("@rules_quarkus//quarkus:defs.bzl", "quarkus_test")

java_library(
    name = "todo-service",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "//libs/todo-model",
        "@maven//:io_quarkus_quarkus_arc",
        "@maven//:jakarta_enterprise_jakarta_enterprise_cdi_api",
    ],
)

java_library(
    name = "todo-service-tests",
    testonly = True,
    srcs = glob(["src/test/java/**/*.java"]),
    deps = [
        ":todo-service",
        "//libs/todo-model",
        "@maven//:io_quarkus_quarkus_junit",
        "@maven//:jakarta_inject_jakarta_inject_api",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
    ],
)

quarkus_test(
    name = "test",
    visibility = ["//visibility:public"],
    deps = [":todo-service-tests"],
)
