package org.acme.contracts;

import org.acme.events.AuditEvent;
import org.acme.grpc.Item;

/** Handwritten contract code that composes types generated by Avro and gRPC. */
public record ContractEnvelope(String itemId, String itemName, String action) {

  public static ContractEnvelope from(Item item, AuditEvent event) {
    return new ContractEnvelope(item.getId(), item.getName(), event.getAction().toString());
  }
}
