package smoke.contracts;

import smoke.contracts.events.AuditEvent;
import smoke.contracts.generated.Contract;

/** Handwritten code composing types generated by two different Quarkus extensions. */
public record ContractEnvelope(String id, String name, String action) {

  public static ContractEnvelope from(Contract contract, AuditEvent event) {
    return new ContractEnvelope(contract.getId(), contract.getName(), event.getAction().toString());
  }
}
