package smoke;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import smoke.contracts.ContractEnvelope;
import smoke.contracts.events.AuditEvent;
import smoke.contracts.generated.Contract;

/**
 * Cross-package proof that a different package can compile and run against types generated by two
 * Quarkus extensions in //contracts, together with that package's handwritten Java.
 */
@Path("/contracts")
public final class ContractResource {

  @GET
  @Produces(MediaType.TEXT_PLAIN)
  public String example() {
    Contract contract = Contract.newBuilder().setId("c-1").setName("Widget").build();
    AuditEvent event =
        AuditEvent.newBuilder().setContractId(contract.getId()).setAction("created").build();
    ContractEnvelope envelope = ContractEnvelope.from(contract, event);
    return envelope.id() + "/" + envelope.name() + "/" + envelope.action();
  }
}
