package org.acme.grpc.consumer;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.acme.contracts.ContractEnvelope;
import org.acme.events.AuditEvent;
import org.acme.grpc.Item;

/**
 * Downstream proof that one library can combine handwritten Java with sources generated by two
 * different Quarkus extensions.
 */
@Path("/contracts/example")
@Produces(MediaType.APPLICATION_JSON)
public class ContractResource {

  @GET
  public ContractEnvelope example() {
    Item item = Item.newBuilder().setId("item-1").setName("Widget").setQuantity(5).build();
    AuditEvent event = AuditEvent.newBuilder().setItemId(item.getId()).setAction("created").build();
    return ContractEnvelope.from(item, event);
  }
}
